### ISSUE TITLE
BREAKING: HA 2023.4 no longer uses app-drawer-layout (IF KIOSK-MODE IS NOT WORKING FOR YOU, CHECK THIS ISSUE INSTEAD OF OPENING A NEW ONE)

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#27]
breaking all custom cards that use this functionality

please see #beta in Discord.

app-drawer-layout was replaced by mwc-drawer
link to Discord: https://discord.com/channels/330944238910963714/427516175237382144/1090920193947074642

I did test the fix that is mentioned, to replace

`querySelector("app-drawer-layout partial-panel-resolver")`

with

`querySelector("app-drawer-layout partial-panel-resolver, mwc-drawer partial-panel-resolver")`

but can only replace

`app-drawer-layout` in the .js file with `mwc-drawer` and that does Not fix the card

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
In `HA 2023.4` not only `app-drawer-layout` has changed. There are multiple changes there so it cannot be fixed by just changing that selector.
I‘ll let this issue open until a version that supports `HA 2023.4` is released.
Regards

**Comment by Mariusthvdb** [comment]
Please do, Bram also announced new changes are to be expected.

Don't know which, maybe Kiosk mode devs can connect with Bram cs.

**Comment by Mariusthvdb** [comment]
amazing, thank you very much, please release!

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
NemesisRE should be back soon and he will take care of the releases, for now you can do this to test it:

* Clone the repo: `git clone git@github.com:NemesisRE/kiosk-mode.git`
* Checkout the branch `git checkout prepare_for_ha_2023.4`
* Run yarn `yarn install`
* Build the plugin `yarn build`
* Copy the JavaScript file in `dist/kiosk-mode.js`
* Test it manually

Take into account that branch has all the changes contained in https://github.com/NemesisRE/kiosk-mode/pull/25 https://github.com/NemesisRE/kiosk-mode/pull/26 and https://github.com/NemesisRE/kiosk-mode/pull/28

Regards

**Comment by gateriderz** [comment]
@elchininet ,

I compiled the new kiosk-mode.js from the branch, removed the old one and replaced with the new one:

kios_mode not working and I get the following errors in the log:

```
https://***/hacsfiles/kiosk-mode/kiosk-mode.js:1:5302 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
https://***/hacsfiles/kiosk-mode/kiosk-mode.js:1:5206 Uncaught TypeError: Cannot read properties of null (reading 'shadowRoot')
```

Thanks

**Comment by elchininet** [comment]
Hi @gateriderz,
In which version of `HA` are you testing?
Also if there is a longer stack trace it will be helpful.
I will take a look ai it later in the afternoon.
Regards

**Comment by gateriderz** [comment]
Hi @elchininet,
Thanks for your quick reply.
I run Home Assistant 2023.4.0b2

This is the only trace I have under my logs:

```
2023-03-31 08:30:20.393 ERROR (MainThread) [frontend.js.latest.202303300] https://***/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128178:1:5302 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
2023-03-31 08:30:20.425 ERROR (MainThread) [frontend.js.latest.202303300] https://***/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128178:1:5302 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
```

**Comment by elchininet** [comment]
Thanks @gateriderz,
I thought that the error was in the current version. The branch is prepared for `2023.4.0b1`, during the development of the new version I‘ll be modifying it until the final `2023.4` is released. I‘ll check the changes in `2023.4.0b2` and I‘ll apply them to the branch.
Regards

**Comment by elchininet** [comment]
Hi @gateriderz,
I cannot reproduce it in `2023.4.0b2`. Please verify that you have the correct version.
Go to the Chrome dev tools, Network tab, filter the resources by `kiosk` and select `kiosk-mode.js`. Then search in the code for `APP_TOOLBAR`, make sure that you get `t.APP_TOOLBAR = "app-toolbar, .toolbar"`.
Let me know if that is the case and I‘ll try to debug further what is happening.
Regards

**Comment by nelsonamen** [comment]
Can you deploy a beta?

**Comment by Mariusthvdb** [comment]
Things to consider:

Menu swipe in from the left is removed from the app.
Hence the hamburger menu is the only way to reach the menu.

It might be a good idea to notify users about that.
Also, it would be awesome if somehow the swipe could be found a way back in Kiosk mode ;/)

Don't know if at all possible ...

**Comment by elchininet** [comment]
> n you deploy a beta?

Hi @nelsonamen, the releases will be done when the owner of the repo is back. For now you can try it with the explanation that I gave above.
Regards

**Comment by elchininet** [comment]
> Things to consider:
> 
> Menu swipe in from the left is removed from the app. Hence the hamburger menu is the only way to reach the menu.
> 
> It might be a good idea to notify users about that. Also, it would be awesome if somehow the swipe could be found a way back in Kiosk mode ;/)
> 
> Don't know if at all possible ...

Yes, that would require a change on the README with an statement that what occurs if one hides the sidebar.
About enabling the swipe from the plugin, that would require more than simple CSS clases, but depending on the final structure of the elements it could be achievable.

**Comment by gateriderz** [comment]
> Hi @gateriderz, I cannot reproduce it in `2023.4.0b2`. Please verify that you have the correct version. Go to the Chrome dev tools, Network tab, filter the resources by `kiosk` and select `kiosk-mode.js`. Then search in the code for `APP_TOOLBAR`, make sure that you get `t.APP_TOOLBAR = "app-toolbar, .toolbar"`. Let me know if that is the case and I‘ll try to debug further what is happening. Regards

Thanks @elchininet , you are correct, I had to reload the kiosk-mode.js again by adding ```kiosk-mode.js?v1``` at the end.

The code shows the proper information:
![image](https://user-images.githubusercontent.com/69553040/229239717-f1184e6b-1c17-4907-b39d-287cc7d3de64.png)

**Comment by elchininet** [comment]
Perfect @gateriderz,
Please, let me know if you have any issue testing it with the new version.
Regards

**Comment by Jeremyhu102** [comment]
Hi,

Is it possible to have a tutorial to make Kiosk-Mode work?

I don't understand anything explained here.

What should be replaced?

Where to find the files, or to install them?

Thx

**Comment by Mariusthvdb** [comment]
Maybe we should have a bit of patience . Why not let the devs here await coming days of Frontend changes until release of HA 2023.4 so we have some certainty things won't break shortly after.

**Comment by elchininet** [comment]
> Hi,
> 
> Is it possible to have a tutorial to make Kiosk-Mode work?
> 
> I don't understand anything explained here.
> 
> What should be replaced?
> 
> Where to find the files, or to install them?
> 
> Thx

Hi @Jeremyhu102,
You would require a bit of knowledge about `Git` and working with terminal commands to build the bundle with [the steps that I left before](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1491024417) and then you can follow the [Manual installation instructions](https://github.com/NemesisRE/kiosk-mode#installation) (after uninstalling the original plugin). But as @Mariusthvdb mentioned, you can wait until Home Assistant `2023.4` is released and the owner of the repo has released a version to support it.

Regards

**Comment by elchininet** [comment]
For those that do not know how to compile the plugin using the code in the working in progress branch, [here you are a gist with the compiled version](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2). You can use this code until the new version is released.

**Comment by Mariusthvdb** [comment]
And notice this

OK, I know you will all hate me for doing this, but believe me it is better to do it now then later 😬 
We will rename `mwc-drawer` to `ha-drawer` during the beta (hopefully next beta)
This means all custom cards that where updated to `mwc-drawer` should now be updated again to `ha-drawer`

**Comment by Jeremyhu102** [comment]
where to find mwc-drawer ?

In kiosk-mode.js I can not find it

**Comment by elchininet** [comment]
> where to find mwc-drawer ?
> 
> In kiosk-mode.js I can not find it

Why do you want to find `mwc-drawer`? This is needed only by someone that wants to change the code of the plugin.

But anyway, if you want to find it, it is not in the current `kiosk-mode.js` because that element its being added in Home Assistant `2023.4`, you need to search for it in the new version that its being prepared in the branch or [in the guist that I posted before](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492972660).

**Comment by elchininet** [comment]
> And notice this
> 
> OK, I know you will all hate me for doing this, but believe me it is better to do it now then later 😬 We will rename `mwc-drawer` to `ha-drawer` during the beta (hopefully next beta) This means all custom cards that where updated to `mwc-drawer` should now be updated again to `ha-drawer`

@Mariusthvdb,

It is better to do the changes when they are released, if it is just a plan it could be changed, as almost everything during development. When the next version is released, if it has more changes, the library should be changed to support them.

**Comment by Mariusthvdb** [comment]
Really sorry, I am on mobile and couldn't find the quote code.

The above is not me stating that, but main Frontend dev Bram in Discord

**Comment by elchininet** [comment]
@Mariusthvdb,
In version `2023.4.0b5` the `mwc-drawer` element has been renamed to `ha-drawer` as Bram commented on Discord. The changes have been pushed to [the development branch](https://github.com/NemesisRE/kiosk-mode/pull/28) and also to [the public gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) with the compiled version.
Regards.

**Comment by Mariusthvdb** [comment]
great!

Ive dl'd the gist, and all seems to be working swell.

Ill add the new options next (hiding the menu items) and will test those, because that will be a major upgrade!

**Comment by Mariusthvdb** [comment]
<img width="311" alt="Scherm­afbeelding 2023-04-03 om 22 25 32" src="https://user-images.githubusercontent.com/33354141/229619647-8caf58db-e6d4-4eb8-9967-7e90402f3906.png">


So this all works just fine!

<img width="199" alt="Scherm­afbeelding 2023-04-03 om 22 25 26" src="https://user-images.githubusercontent.com/33354141/229619730-da27533c-cfad-4bad-8513-ad037041eddc.png">

great, and congrats!

there is but 1 gripe.... might be an edge case, as I probably will always want tp have at least 1 menu item there, but hiding all menu items takes away the whole triple dot icon.

and, that is the anchor for my menu item template using card-mod-themes:

```
      /* Optionally set the three-dots transparency,
         to allow for a replacement template text. */
      ha-button-menu {
        color: {{'transparent' if is_state('input_boolean.menu_options_template','on')}};
      }

      /* Optionally set a replacement template text. */
      ha-button-menu::before {
        content: "{%- if is_state('input_boolean.menu_options_template','on') %}
                  {{- states('sensor.buienradar_symbol')}} |
                  {{- states('sensor.buienradar_temperature')}} °C
                  {%- endif %}";
        color: var(--app-header-text-color);
        visibility: visible;
        position: relative;
        top: 24px;
        white-space: nowrap;
      }
```

I would like to ask if anything can be done here, to hide the menu-items, but allow this mod to be there anyways.

**Comment by Mariusthvdb** [comment]
while we're at it, and this might be a new FR, so if you'd agree, I can write it up separately:

I still have these:

```
      /* Hide chevrons
      paper-tabs$: |
        .not-visible {
          display: none;
        } */
```
which before, used to do as stated: hide the chevrons in the menu bar. Saves us 2 icons yet again...

also, there's a Help icon in the edit mode that can be ditched:

```
      /* This hides the help button when in edit mode*/
      a.menu-link[target="_blank"] {
        {% if is_state('input_boolean.hide_help','on') %}display: none;{% endif %}
      }
```

and the above does work still. I would love to have all of these Dashboard mods in a single package, so maybe have a look?

Btw, I believe you should next rename the custom card, it has grown beyond Kiosk mode only...

again, thanks!

**Comment by elchininet** [comment]
Hi @Mariusthvdb,

Yes, we can discuss this in a separate issue to keep this one for `HA 2023.4` issue. (Maybe NemesisRE could open a discussion section for these topics).

But the easiest solution that I see (because it is not nice an empty menu when all its items are being hidden) is to create another option to hide automatically the overflow menu if all its items are hidden. In that way you can choose if you want that behaviour or not.

Regards

**Comment by Jeremyhu102** [comment]
Hi,

Still does not work

Home Assistant 2023.4.0b6
Supervisor 2023.04.0
Operating System 10.0.rcp

**Comment by Mariusthvdb** [comment]
yes it does...

you probably need to install it in a different folder from HACS, and set the path to that resource. HACS can be difficult to persuade when using manual edited files

**Comment by elchininet** [comment]
Hi @Jeremyhu102,
I have tested it on `2023.4.0b5`, maybe `2023.4.0b6` has more changes. I'll take a look later. Please, follow the discussion and make sure that you are loading the correct version with the instructions that I gave before.
Regards.

**Comment by elchininet** [comment]
Hi @Jeremyhu102,
I have tested it on `2023.4.0b6` and it works on my side. Please, describe exactly what do you mean with "still does not work", if there are certain features that are not working properly for you or if you receive any errors on the console.
Regards.

**Comment by homeyjoenka** [comment]
hello should the kiosk mode  with latest beta work do i understand that right?

**Comment by pedolsky** [comment]
I'm running beta7 without any problems.

**Comment by Jeremyhu102** [comment]
Which file to edit?
Where to find this file?
What should be modified?
How to modify it?

I tried to modify this: 

/config/www/community/kiosk-mode/kiosk-mode.js

it does not work

**Comment by chicknlil** [comment]
I stuck mine in /www/ removed the links in resources to the HACS version, and told it to look at /local/kiosk-mode.js instead.  Working fine for me.

**Comment by Jeremyhu102** [comment]
> I stuck mine in /www/ removed the links in resources to the HACS version, and told it to look at /local/kiosk-mode.js instead. Working fine for me.

paste what in /www/?     The Folder Kiosk-mode

there is no complete tutorial?  step by step

**Comment by chicknlil** [comment]
They've given you two resources to fix it yourself, I even offered where I put mine to make it work.

If you need more help than that, it's probably best you wait for them to release the fixed version.

**Comment by Jeremyhu102** [comment]
> They've given you two resources to fix it yourself, I even offered where I put mine to make it work.
> 
> If you need more help than that, it's probably best you wait for them to release the fixed version.

I did not see anything

or without explanation

**Comment by chicknlil** [comment]
[You were given the instructions four days ago.](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492947745) . 

If you can't do either of those things, there's really not much anyone else here can do to help you.

**Comment by elchininet** [comment]
> hello should the kiosk mode with latest beta work do i understand that right?

Hi @homeyjoenka, the new version is not released yet, but if you follow the instructions given in this thread you can make it work.

**Comment by elchininet** [comment]
> I'm running beta7 without any problems.

@pedolsky good to know it 👌

I‘ll try to do an extensive test in `2023.4.0b7` later on to see if everything is OK because I have been tested it until `2023.4.0b6`

**Comment by elchininet** [comment]
> Hi,
> 
> Which file to edit? Where to find this file? What should be modified? How to modify it?
> 
> I tried to modify this:
> 
> /config/www/community/kiosk-mode/kiosk-mode.js
> 
> it does not work
> 
> Thx

Hi @Jeremyhu102,
You need to follow [the instructions that I gave you some days ago](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492947745). How to install the library manually is documented in the README of the repo.
Regards

**Comment by elchininet** [comment]
Tested in `2023.4.0b7` it is working properly.

**Comment by Homeassistjoenka** [comment]
When have we update?

**Comment by elchininet** [comment]
Hi @Homeassistjoenka,
You should wait until the owner of the repo review the changes, merge the branch and release a new version.
He should be back around these days.
Regards

**Comment by chicknlil** [comment]
Hey @elchininet (& @NemesisRE ) ... with this patch version and using `?kiosk` , I have a sliver of what probably remains from the sidebar still in view on my devices that I'm using kiosk-mode on.  Is this expected behavior because of the 2023.4 beta breaking changes, or is this something that can be eliminated, as it was before?

No worries either way, more curiosity than anything else.

**Comment by elchininet** [comment]
Hi @chicknlil,
What you are describing is not expected. Please, open an issue with some screenshots so we can debug there what is happening.
Regards

**Comment by bkr1969** [comment]
I've tried following the steps here and cannot get it to work either.  I replaced the .js file with the compiled code linked here and still get a header and errors in my logs.

**Comment by elchininet** [comment]
Hi @bkr1969,
You need to force the browser to load the new version, you can use multiple techniques for that (e.g. [here](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492651263) or [here](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1497768027))

**Comment by bkr1969** [comment]
OK. That helped.  So when the fix is implemented will I need to delete the resource and .js file from /www?

**Comment by elchininet** [comment]
@bkr1969,
Good to know it. 
Yes, when the fix is implemented and a new version is released, you just need to delete the manual `JavaScript` file, remove the resource that you created and install the plugin again through `HACS`.

**Comment by niekniek89** [comment]
I got the fix working, and the kiosk bar disappeared again.

I have an issue with swiping to the right (to display the sidebar). 
does that also apply to this issue?

otherwise this comment can be removed.

**Comment by pergolafabio** [comment]
swiping left is idd an companion issue

**Comment by elchininet** [comment]
@niekniek89,
Please, [check this comment](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492443363).

**Comment by niekniek89** [comment]
> @niekniek89, Please, [check this comment](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492443363).

I just updated the HA IOS app, and swiping for the sidebar works again!

**Comment by akhan999** [comment]
when is the fix planned to be released?

**Comment by akhan999** [comment]
ill wait for his return

**Comment by DerEmder** [comment]
I updated to 1.8.0 but that did not work (updating for 5 minutes then i stopped it). I removed 1.7.8, restarted, cleared cache and installed 1.8.0 fresh. Restarted again. Refreshed my dashboard and nope - still sidebar and header bar visible. The same on my mobile screen (old Android tablet). No change whatsoever. What eles should I restart, refresh or whatever? Double checked the yaml and the neccessary entries. Maybe I'm blind and don't see the problem.

![Bildschirmfoto vom 2023-04-06 17-37-15](https://user-images.githubusercontent.com/91392202/230429102-2a2af494-7799-47bf-bd54-b63e1ba1ba6f.jpg)
![Bildschirmfoto vom 2023-04-06 17-37-39](https://user-images.githubusercontent.com/91392202/230429104-b9748a7a-87aa-47d0-a091-fd564b0569e1.jpg)

**Comment by chicknlil** [comment]
> I updated to 1.8.0 but that did not work (updating for 5 minutes then i stopped it). I removed 1.7.8, restarted, cleared cache and installed 1.8.0 fresh. Restarted again. Refreshed my dashboard and nope - still sidebar and header bar visible. The same on my mobile screen (old Android tablet). No change whatsoever. What eles should I restart, refresh or whatever? Double checked the yaml and the neccessary entries. Maybe I'm blind and don't see the problem.

It's not a HACS update currently. You need to follow the instructions in [this post](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1491024417).

**Comment by DerEmder** [comment]
? There was no mentioning of this in the advertised update. Sorry, I'm lost here. I will have to wait for a real update ...

**Comment by chicknlil** [comment]
> ? There was no mentioning of this in the advertised update. Sorry, I'm lost here. I will have to wait for a real update ...

Actually, I didn't realize a new update had been pushed an hour ago. 

Had you previously used the "patch" version or the "original" kiosk-mode? Both of those would need to be removed (including from resources) for the update to work properly.

**Comment by DerEmder** [comment]
I did not patch anything, I just had 1.7.8 installed. Updating did not work, I stopped it after waiting for 10 minutes. As I wrote - I removed everything and installed 1.8.0 - but .. haha . .there is no kiosk-mode.js in it. Instead - this is the contents after 'installing':

![Bildschirmfoto vom 2023-04-06 17-43-14](https://user-images.githubusercontent.com/91392202/230435972-a7a91ea8-835d-4222-b3be-4515b31cc956.jpg)

**Comment by elchininet** [comment]
> I updated to 1.8.0 but that did not work (updating for 5 minutes then i stopped it). I removed 1.7.8, restarted, cleared cache and installed 1.8.0 fresh. Restarted again. Refreshed my dashboard and nope - still sidebar and header bar visible. The same on my mobile screen (old Android tablet). No change whatsoever. What eles should I restart, refresh or whatever? Double checked the yaml and the neccessary entries. Maybe I'm blind and don't see the problem.
> 
> ![Bildschirmfoto vom 2023-04-06 17-37-15](https://user-images.githubusercontent.com/91392202/230429102-2a2af494-7799-47bf-bd54-b63e1ba1ba6f.jpg) ![Bildschirmfoto vom 2023-04-06 17-37-39](https://user-images.githubusercontent.com/91392202/230429104-b9748a7a-87aa-47d0-a091-fd564b0569e1.jpg)

Hi @DerEmder,
That version doesn‘t have the fix, [the branch is not merged yet](https://github.com/NemesisRE/kiosk-mode/pull/28). That version contains just [these changes](https://github.com/NemesisRE/kiosk-mode/pull/25).

**Comment by elchininet** [comment]
> I did not patch anything, I just had 1.7.8 installed. Updating did not work, I stopped it after waiting for 10 minutes. As I wrote - I removed everything and installed 1.8.0 - but .. haha . .there is no kiosk-mode.js in it. Instead - this is the contents after 'installing':
> 
> ![Bildschirmfoto vom 2023-04-06 17-43-14](https://user-images.githubusercontent.com/91392202/230435972-a7a91ea8-835d-4222-b3be-4515b31cc956.jpg)

This is weird, I‘ll check it.

**Comment by DerEmder** [comment]
This is all confusing. So why is this advertised in HACS as the latest release? I don't care about new features or the mouse thingy - I only care about fixing the bugs so kiosk mode is working again. I guess I will have to wait until a new release. My knowledge is not deep enough to try the 'manual fix' explained above.

**Comment by Homeassistjoenka** [comment]
@chicknlil  do you need to add that in the download url? that
?kiosk

**Comment by DerEmder** [comment]
How can this even work if there is no kiosk-mode.js installed? 

And no, it does not work here - neither ?kiosk nor any other way. I try this on my tablet and my dekstop computer - both with chrome browsers. It just does not work for me. What do you mean with 'latest HACS version' ? The 1.8.0 ?

The ressource entry gets removed automatically if you remove kiosk-mode.

I just installed the 'update' again out of frustration- this time it did not hang and installed. But still - no kiosk-mode.js inside and no functionality. No luck here. Any idea?

**Comment by chicknlil** [comment]
> @chicknlil do you need to add that in the download url? that ?kiosk

Into the path in your address bar. So like` http://homeassistant.local:8123/lovelace/kiosk` would become `http://homeassistant.local:8123/lovelace/kiosk?kiosk`

**Comment by DerEmder** [comment]
Hmm, this is the list of ressources after installing 1.8.0. This can't be right, can it?

![Bildschirmfoto vom 2023-04-06 18-47-31](https://user-images.githubusercontent.com/91392202/230444094-43b7dd22-af5e-4b0b-a148-664abb71055a.jpg)

**Comment by DerEmder** [comment]
> > @chicknlil do you need to add that in the download url? that ?kiosk
> 
> Into the path in your address bar. So like` http://homeassistant.local:8123/lovelace/kiosk` would become `http://homeassistant.local:8123/lovelace/kiosk?kiosk`

Yes, I know that. It does **not** work here. Of course it does not. There is no kiosk-mode.js installed! I posted the contents of 1.8.0 already - no kiosk-mode.js, just rollup....js. Nothing else. I tried it now for the fifth time.

**Comment by Homeassistjoenka** [comment]
> > @chicknlilMoet je dat toevoegen aan de download-URL? dat? kiosk
> 
> In het pad in je adresbalk. Dus zoals ` http://homeassistant.local:8123/lovelace/kiosk`zou worden`http://homeassistant.local:8123/lovelace/kiosk?kiosk`

so? http://192.168.6.208:8123/lovelace/kiosk?kiosk=

**Comment by chicknlil** [comment]
> Yes, I know that. It does **not** work here. Of course it does not. There is no kiosk-mode.js installed! I posted the contents of 1.8.0 already - no kiosk-mode.js, just rollup....js. Nothing else. I tried it now for the fifth time.

I wasn't answering you. :) But given your recent image, it looks like your resource for kiosk-mode needs deleting (it appears corrupted). Try that (and also completely uninstall kiosk-mode from HACS), restart HA, then try downloading the most recent version from HACS again.

I had completely eliminated the HACS version while I used the patched version, and installed it fresh, and mine is working with no issues.

> so? http://192.168.6.208:8123/lovelace/kiosk?kiosk=

I don't believe you'd need the = ... but yeah, make sure the /kiosk is the path to the view you're trying to see without header/sidebar.

**Comment by DerEmder** [comment]
Sorry, my bad. Need glasses :)

Anyway - I will try after my lunch - I need brain energy first.

By the way - I removed the kiosk-mode line from the ressource file **before** installing 1.8.0. **After** installing 1.8.0 the line re-appears again.

Laters ...

**Comment by elchininet** [comment]
> This is all confusing. So why is this advertised in HACS as the latest release? I don't care about new features or the mouse thingy - I only care about fixing the bugs so kiosk mode is working again. I guess I will have to wait until a new release. My knowledge is not deep enough to try the 'manual fix' explained above.

Because it is, "latest release" just mean that, the latest one. It doesn‘t mean "it fixes your specific issue" or anything like that. If you "only care about fixing the bugs so kiosk mode is working again" you need to wait for the release that fixes that, and as I mentioned, it was not the one that you mentioned and it will not be the next one, and possible the next one either (there is a list of pull requests waiting for being released).

**Comment by DerEmder** [comment]
But that **IS** the specific issue this whole thread is about, isn't it? If the software does not work at all - what good are other updates for other issues? It does not make sense to me. But anyway - lunch time

**Comment by elchininet** [comment]
@DerEmder this thread is about this issue, latest release (that was released by the owner of the repo is not). I think that you are forgetting that everyone here works in this for free and we just invest our time here to contribute to the community, as myself because I am only a contributor.

**Comment by pergolafabio** [comment]
i also updated to 1.8.0 , and i see now the rollup files
removed them, and using the one from gist and point the resource correctly

**Comment by elchininet** [comment]
> i also updated to 1.8.0 , and i see now the rollup files removed them, and using the one from gist and point the resource correctly

Yes, the issue with the latest release should be fixed when this gets merged and released:

https://github.com/NemesisRE/kiosk-mode/pull/37

**Comment by besiktas97** [comment]
It doesn't work for me. Have changed this path: /local/kiosk-mode.js?v=1.8.0 and copied the latest kiosk-mode.js to my HA. Removed the previous version of kiosk-mode v1.7.8 and still not working :(

**Comment by elchininet** [comment]
Hi @besiktas97,
What do you mean with the latest version?
Check the instructions given at the beginning of the thread, you should uninstall the installed version.
Regards

**Comment by besiktas97** [comment]
> Hi @besiktas97, What do you mean with the latest version? Check the instructions given at the beginning of the thread, you should uninstall the installed version. Regards

Hello elchininet,

I did a uninstall of the previous version and did a manual installation. the path I made /local/kiosk-mode.js?v=1.8.0 and even I tried /local/kiosk-mode.js?v=1.7.8 and the side bar is still vissible.

**Comment by pergolafabio** [comment]
You need the version from gist,

**Comment by elchininet** [comment]
Did you use the compiled version provided in this thread?
Are you able to see `kiosk-mode.js` in the network tab of your browser?

**Comment by besiktas97** [comment]
cant clone it: 
![image](https://user-images.githubusercontent.com/76499056/230463877-3fcb72b4-a26f-4ddb-b816-e3e2ef9a2706.png)

**Comment by elchininet** [comment]
@besiktas97,
Please, take your time and read the thread, [there is public gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) with the compiled version that you can install. You don‘t need to clone the repo and compile the code.
Regards.

**Comment by DerEmder** [comment]
> * Rollback to a version that it is compatible

Not really an option at this moment.

> * Try to solve it with the workarounds that the community creates "for free" for you

Yes, I know. It is free. I don't pay money for it. Is that what you mean? I pay for it with my precious time I could spent in doing other things. So i also use my spare time "for free" to help the dev to make it work again. So please don't lecture me about "free" and Open-Source - I am fully aware of that. LetÄs put it this way: it is a taking and giving and hopefulyl we will all find the right balance.

> * Wait for the release that fixes the issue is released

I will.

**Comment by DerEmder** [comment]
> @besiktas97, Please, take your time and read the thread, [there is public gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) with the compiled version that you can install. You don‘t need to clone the repo and compile the code. Regards.

I tried that piece of Javascript from gist and installed it manually. It does not work here. It was actually the first thing I did after reading it. Maybe I did it wrong, I don't know. But I did exactly what was posted above. And I was also unable to clone the repo with the same error message as posted above (Permission denied).

**Comment by elchininet** [comment]
> > @besiktas97, Please, take your time and read the thread, [there is public gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) with the compiled version that you can install. You don‘t need to clone the repo and compile the code. Regards.
> 
> I tried that piece of Javascript from gist and installed it manually. It does not work here. It was actually the first thing I did after reading it. Maybe I did it wrong, I don't know. But I did exactly what was posted above. And I was also unable to clone the repo with the same error message as posted above (Permission denied).

Yes, you did it wrong for sure because it works. You just need to check all the people here that have that version working (including myself).

**Comment by elchininet** [comment]
>And I was also unable to clone the repo with the same error message as posted above (Permission denied).

I‘ll change the instructions, you can only clone a fork of it.

**Comment by DerEmder** [comment]
> You just need to check all the people here that have that version working (including myself).

I only read from people where it does **not** work. You are the only one who says it works. So I assume it **should** work. I will try again and report back if I succeed.

**Comment by pergolafabio** [comment]
For me gist is also working, I have hidden the title bar again , used the gist, removed the 2 files on the kiosk folder, downloaded the gist there...

Restarted , clear cache, that's it

**Comment by DerEmder** [comment]
> I‘ll change the instructions, you can only clone a fork of it.

I don't even know what that means and how to do it. I never used Github. So, that's a bit too complicated for me at this point. I am just a user, not a programmer

**Comment by elchininet** [comment]
@DerEmder,

Just as a reference so you can check that what you are saying is not accurate:

https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492651263

https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1494911564

https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1497265590

https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1497768027

https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1498226442

https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1498928065

**Comment by DerEmder** [comment]
> For me gist is also working, I have hidden the title bar again , used the gist, removed the 2 files on the kiosk folder, downloaded the gist there...
> 
> Restarted , clear cache, that's it

Thanks, so it should work. I will do the same now. 

So you have 1.7.8 installed, removed the two files (.js and .gz) from kiosk-mode folder and uploaded the javascript from gist (kiosk-mode.js) into the kiosk-mode folder. Is that correct? 

Then clearing cache etc. and it should work?

**Comment by DerEmder** [comment]
> @DerEmder,
> 
> Just as a reference so you can check that what you are saying is not accurate:

I apologize - overlooked them.

**Comment by pergolafabio** [comment]
Just install 1.8.0,doesnt mather, remove files afterwarda, place the gist file there, point correctly with resource , to make it work for sure, add ?v1 add the end in your resource... Then clear cache, restart

**Comment by besiktas97** [comment]
> Just install 1.8.0,doesnt mather, remove files afterwarda, place the gist file there, point correctly with resource , to make it work for sure, add ?v1 add the end in your resource... Then clear cache, restart

I have removed the old version, but when I want to download it O cant download verdion 1.8.0. Only 1.7.8, tonight I will digg more into it.

**Comment by pergolafabio** [comment]
Yeah doesn't mather , you need to remove files anyways, but I suggest you to wait for next version , they are working on it, be patient

**Comment by besiktas97** [comment]
> @besiktas97,
> 
> Forget the version `1.8.0` it was deleted because it was a wrong release. Just follow the instructions:
> 
> * Uninstall kiosk-mode
> 
> * Install the gist manually with the instructions given in the README
> 
> * Clear cache and that should be enough
> 
> 
> 
> Anyway, the pull request that solves the issue [is ready to merge](https://github.com/NemesisRE/kiosk-mode/pull/28). When @NemesisRE take a look at it and merge it, a new version could be released.

Thanks then I will wait I guess for the new release. Patient patient :-)

**Comment by DerEmder** [comment]
Ha, that did work. I guess I forgot the ?v1 thing in the ressources file. Header bar is gone now, sidebar still there. But one problem at a time.

Thanks @pergolafabio and @elchininet

Now will wait for the release with a fix.

**Comment by DerEmder** [comment]
A last note before I go to sleep - now kiosk mode even works where it is not even part of the yaml. Now the header bar (not the sidebar) is removed in **all** views and dashboards no matter if there is an entry with kiosk_mode in the yaml or not. Doesn't bother me too much because I can disable it with _?disable_km_ where I need it.

**Comment by elchininet** [comment]
Hi guys. The new version `1.8.1`is released, I have already removed my manual fix and installed it again and it is working properly.

Thanks to all of you for the feedback during the testings 👍

Please, if you notice something, feel free to open an issue with it, closing this issue.

**Comment by elchininet** [comment]
> A last note before I go to sleep - now kiosk mode even works where it is not even part of the yaml. Now the header bar (not the sidebar) is removed in **all** views and dashboards no matter if there is an entry with kiosk_mode in the yaml or not. Doesn't bother me too much because I can disable it with _?disable_km_ where I need it.

Hi @DerEmder,

Feel free to create an issue describing what you are facing.

**Comment by gzzyyt** [comment]
[https://github.com/gzzyyt/find-music/blob/main/1.png](url)[https://github.com/gzzyyt/find-music/blob/main/2.jpg](url)After upgrading to 1.8.1, there was no problem with the computer browser webpage when the header was hidden, and it displayed normally. However, there was a black box below my iPad, which prevented me from displaying everything

**Comment by scooper1** [comment]
I had to reboot and redownload 1.81 to get old version out of system.   Seams to working ok
Thanks

**Comment by Homeassistjoenka** [comment]
Morning, Thank you so much for the update, kiosk mode, grate job

**Comment by elchininet** [comment]
> I've updated to version 1.8.1, cleared the cache, and rebooted, but I'm still getting the error below.
> 
> Logger: frontend.js.latest.202304061
> Source: components/system_log/init.py:257
> First occurred: 09:22:39 (4 occurrences)
> Last logged: 10:38:18
> 
> https://ooooo/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:13:44 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
> https://ooooo/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:57:96 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
> 
> Home Assistant 2023.4.1
> Supervisor 2023.04.0
> Operating System 9.5
> Frontend 버전: 20230406.1 - latest

Hi @Murianwind,
Please, let‘s discuss your issue here.
Could you follow [these steps](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492407004) but search for `TOOLBAR` and let me know if you can find this in your code `t.TOOLBAR = ".toolbar",`?
Regards

**Comment by akhan999** [comment]
Awesome all fixed with the latest update. Thank you
